// This file was autogenerated by calcdeps.py
goog.addDependency("./lib/deferred/deferred.js", ['Deferred'], []);
goog.addDependency("./lib/deferred/index.js", [], []);
goog.addDependency("./lib/mongo2sql/examples.js", [], []);
goog.addDependency("./lib/mongo2sql/mongo2sql.js", ['mongo2sql'], []);
goog.addDependency("./lib/string.inflection/index.js", [], []);
goog.addDependency("./lib/string.inflection/inflection.js", ['string.inflection', 'string.inflection.Rules'], []);
goog.addDependency("./lib/uuid/uuid.js", ['uuid'], []);
goog.addDependency("./src/deps.js", [], []);
goog.addDependency("./src/model.js", ['nativish.Model'], ['uuid', 'goog.json', 'Deferred', 'string.inflection', 'nativish.SQLStatement', 'nativish.SQLStatement.Modes']);
goog.addDependency("./src/sql-statement.js", ['nativish.SQLStatement', 'nativish.SQLStatement.Modes'], ['mongo2sql', 'Deferred']);
